/*
HtmlOsisConverter - Converts NeÜ Bible HTML files to OSIS XML.
Copyright (C) 2022 PhysXCoder

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

namespace NeueHtmlOsisConverter.Bible;

/// <summary>
/// Enum of all books that have been or could be in a bible canon.
/// Enum values match USFM 3 specification numbers where possible, see https://ubsicap.github.io/usfm/identification/books.html
/// </summary>
public enum Book
{ 
    Genesis = 1,
    Exodus = 2,
    Leviticus = 3,
    Numbers = 4,
    Deuteronomy = 5,
    Joshua = 6,
    Judges = 7,
    Ruth = 8,
    FirstSamuel = 9,
    SecondSamuel = 10,
    FirstKings = 11, 
    SecondKings = 12, 
    FirstChronicles = 13, 
    SecondChronicles = 14, 
    Ezra = 15, 
    Nehemiah = 16, 
    Esther = 17, 
    Job = 18, 
    Psalms = 19, 
    Proverbs = 20, 
    Ecclesiastes = 21, 
    SongOfSongs = 22, 
    Isaiah = 23, 
    Jeremiah = 24, 
    Lamentations = 25, 
    Ezekiel = 26, 
    Daniel = 27, 
    Hosea = 28, 
    Joel = 29, 
    Amos = 30, 
    Obadiah = 31, 
    Jonah = 32, 
    Micah = 33, 
    Nahum = 34, 
    Habakkuk = 35, 
    Zephaniah = 36, 
    Haggai = 37, 
    Zechariah = 38, 
    Malachi = 39, 
    Matthew = 41, 
    Mark = 42, 
    Luke = 43, 
    John = 44, 
    Acts = 45, 
    Romans = 46, 
    FirstCorinthians = 47, 
    SecondCorinthians = 48, 
    Galatians = 49, 
    Ephesians = 50, 
    Philippians = 51, 
    Colossians = 52, 
    FirstThessalonians = 53, 
    SecondThessalonians = 54, 
    FirstTimothy = 55, 
    SecondTimothy = 56, 
    Titus = 57, 
    Philemon = 58, 
    Hebrews = 59, 
    James = 60, 
    FirstPeter = 61, 
    SecondPeter = 62, 
    FirstJohn = 63, 
    SecondJohn = 64, 
    ThirdJohn = 65, 
    Jude = 66, 
    Revelation = 67,
    Tobit = 68,
    Judith = 69,
    EstherGreek = 70,
    WisdomOfSolomon = 71,
    Sirach = 72,
    Baruch = 73,
    LetterOfJeremiah = 74,
    SongOfTheThreeYoungMen = 75,
    Susanna = 76, 
    BelAndTheDragon = 77,
    FirstMaccabees = 78,
    SecondMaccabees = 79,
    ThirdMaccabees = 80,
    FourthMaccabees = 81,
    FirstEsdras = 82,
    SecondEsdras = 83,
    PrayerOfManasseh = 84,
    Psalm151 = 85,
    Odae = 86,
    PsalmsOfSolomon = 87,
    ExtraMaterialA = 94,
    ExtraMaterialB = 95,
    ExtraMaterialC = 96,
    ExtraMaterialD = 97,
    ExtraMaterialE = 98,
    ExtraMaterialF = 99,
    ExtraMaterialG = 100, 
    
    // The following books have non-numerical numbers in USFM 3 (e.g. Ezra Apocalypse = A4) and have values greater than 100 here.
    EzraApocalypse = 101,
    FifthEzra = 102,
    SixthEzra = 103,
    DanielGreek = 104,
    Psalms152155 = 104,
    SecondBaruchApocalypse = 106,
    LetterOfBaruch = 107,
    Jubilees = 108,
    Enoch = 109,
    FirstMeqabyan = 110,
    SecondMeqabyan = 111,
    ThirdMeqabyan = 112,
    Reproof = 113, 
    FourthBaruch = 114, 
    LetterToTheLaodiceans = 115,
    FrontMatter = 116,
    BackMatter = 117,
    OtherMatter = 118,
    IntroductionMatter = 119,
    Concordance = 120, 
    Glossary = 121,
    TopicalIndex = 122,
    NamesIndex = 123,
}